### ISSUE TITLE
Errors when running example

### ISSUE THREAD

**Issue by Daiver** [albu/albumentations#29]
Hello! I just found that example from https://albumentations.readthedocs.io/en/latest/examples.html sometime gives me `TypeError` and OpenCV related errors

Here is minimal example
```
import albumentations
from albumentations import (
    HorizontalFlip, IAAPerspective, ShiftScaleRotate, CLAHE, RandomRotate90,
    Transpose, ShiftScaleRotate, Blur, OpticalDistortion, GridDistortion, HueSaturationValue,
    IAAAdditiveGaussianNoise, GaussNoise, MotionBlur, MedianBlur, IAAPiecewiseAffine,
    IAASharpen, IAAEmboss, RandomContrast, RandomBrightness, Flip, OneOf, Compose
)
import numpy as np

def strong_aug(p=.5):
    return Compose([
        RandomRotate90(),
        Flip(),
        Transpose(),
        OneOf([
            IAAAdditiveGaussianNoise(),
            GaussNoise(),
        ], p=0.2),
        OneOf([
            MotionBlur(p=.2),
            MedianBlur(blur_limit=3, p=.1),
            Blur(blur_limit=3, p=.1),
        ], p=0.2),
        ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.2, rotate_limit=45, p=.2),
        OneOf([
            OpticalDistortion(p=0.3),
            GridDistortion(p=.1),
            IAAPiecewiseAffine(p=0.3),
        ], p=0.2),
        OneOf([
            CLAHE(clip_limit=2),
            IAASharpen(),
            IAAEmboss(),
            RandomContrast(),
            RandomBrightness(),
        ], p=0.3),
        HueSaturationValue(p=0.3),
    ], p=p)

print(albumentations.__version__)

for i in range(1000):
    print(i)
    image = np.ones((300, 300))
    mask = np.ones((300, 300))
    whatever_data = "my name"
    augmentation = strong_aug(p=0.9)
    data = {"image": image, "mask": mask, "whatever_data": whatever_data, "additional": "hello"}
    augmented = augmentation(**data)
    image, mask, whatever_data, additional = augmented["image"], augmented["mask"], augmented["whatever_data"], augmented["additional"]

```

First full error message
```
Traceback (most recent call last):
  File "a.py", line 49, in <module>
    augmented = augmentation(**data)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/composition.py", line 17, in __call__
    data = t(**data)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 22, in __call__
    return {key: self.targets.get(key, lambda x, **p: x)(arg, **params) for key, arg in kwargs.items()}
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 22, in <dictcomp>
    return {key: self.targets.get(key, lambda x, **p: x)(arg, **params) for key, arg in kwargs.items()}
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/augmentations/transforms.py", line 414, in apply
    assert image.dtype == np.uint8 or self.hue_shift_limit < 1.
TypeError: '<' not supported between instances of 'tuple' and 'float'

```

Second full error message
```
OpenCV(3.4.1) Error: Unsupported format or combination of formats () in medianBlur, file /io/opencv/modules/imgproc/src/smooth.cpp, line 4597
Traceback (most recent call last):
  File "a.py", line 49, in <module>
    augmented = augmentation(**data)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/composition.py", line 17, in __call__
    data = t(**data)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/composition.py", line 33, in __call__
    data = t(**data)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 22, in __call__
    return {key: self.targets.get(key, lambda x, **p: x)(arg, **params) for key, arg in kwargs.items()}
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 22, in <dictcomp>
    return {key: self.targets.get(key, lambda x, **p: x)(arg, **params) for key, arg in kwargs.items()}
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/augmentations/transforms.py", line 551, in apply
    return F.median_blur(image, ksize)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/augmentations/functional.py", line 193, in median_blur
    return cv2.medianBlur(img, ksize)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/smooth.cpp:4597: error: (-210)  in function medianBlur

```

Third full error message
```
OpenCV(3.4.1) Error: Assertion failed (depth == 0 || depth == 2 || depth == 5) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11109
Traceback (most recent call last):
  File "a.py", line 49, in <module>
    augmented = augmentation(**data)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/composition.py", line 17, in __call__
    data = t(**data)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/composition.py", line 33, in __call__
    data = t(**data)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 22, in __call__
    return {key: self.targets.get(key, lambda x, **p: x)(arg, **params) for key, arg in kwargs.items()}
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/core/transforms_interface.py", line 22, in <dictcomp>
    return {key: self.targets.get(key, lambda x, **p: x)(arg, **params) for key, arg in kwargs.items()}
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/augmentations/transforms.py", line 597, in apply
    return F.clahe(img, clip_limit, self.tile_grid_size)
  File "/home/daiver/.local/lib/python3.6/site-packages/albumentations/augmentations/functional.py", line 156, in clahe
    img = cv2.cvtColor(img, cv2.COLOR_RGB2LAB)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11109: error: (-215) depth == 0 || depth == 2 || depth == 5 in function cvtColor

```

My Python version: `3.6.3`
albumentations version: `0.0.4`

PS Sorry for my poor English

**Comment by creafz** [comment]
Could you try to replace these 2 lines:
```
image = np.ones((300, 300))
mask = np.ones((300, 300))
```

with this:

```
image = np.ones((300, 300, 3), dtype=np.uint8)
mask = np.ones((300, 300), dtype=np.uint8)
```

and see whether the errors still occur?

By default, np.ones returns a ndarray with the float64 data type, and some augmentations may work incorrectly with it. For now, the library fully supports uint8 inputs, but we are working on adding support for float input types, and I think we will release it soon.

**Comment by Daiver** [comment]
Looks like uint8 solves all problems. Thank you!

**Comment by Sanket-DataEnt** [comment]
Have you started supporting integer datatype in albumentation 0.4.5

**Comment by Dipet** [comment]
Pass data into augmentations as named arguments. Examples: https://github.com/albumentations-team/albumentations_examples/blob/master/notebooks/showcase.ipynb

**Comment by anonymousleo** [comment]
I am trying to run a code repository downloaded from GitHub as it is mentioned in the instruction of that but getting following error.

TypeError: __init__() missing 1 required positional argument: 'image_paths'
I am having this error at the code line 63 (preprocessing = preprocessing).
When I srat the program in debug mode I shows following error
unable to get repr for <class 'albumentations.core.composition.compose'>
```
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
import torch

from skimage import io

from utils import adjust_sar_contrast, compute_building_score, plot_images

sys.path.append('/home/salman/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work')
from spacenet6_model.configs.load_config import get_config_with_previous_experiment
from spacenet6_model.datasets import SpaceNet6TestDataset
from spacenet6_model.models import get_model
from spacenet6_model.transforms import get_augmentation, get_preprocess

# select previous experiment to load
exp_id = 14
exp_log_dir = "/home/salman/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/logs"  # None: use default

# select device to which the model is loaded
cuda = True
if cuda:
    device = 'cuda'
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'
else:
    device = 'cpu'
    os.environ['CUDA_VISIBLE_DEVICES'] = ''

# overwrite default config with previous experiment
config = get_config_with_previous_experiment(exp_id=exp_id, exp_log_dir=exp_log_dir)

# overwrite additional hyper parameters
config.MODEL.DEVICE = device

config.WEIGHT_ROOT = "/home/salman/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/"
config.MODEL.WEIGHT = f"/home/salman/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/weights/exp_{exp_id:04d}/model_best.pth"
config.INPUT.MEAN_STD_DIR = "/home/salman/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/models/image_mean_std/"
config.INPUT.TEST_IMAGE_DIR = "/home/salman/data/SN6_buildings_AOI_11_Rotterdam_test_public/test_public/AOI_11_Rotterdam/SAR-Intensity"
config.INPUT.SAR_ORIENTATION="/home/salman/Downloads/SpaceNet_SAR_Buildings_Solutions-master/4-motokimura/tmp/work/static/SAR_orientations.txt"
config.TRAIN_VAL_SPLIT_DIR="/home/salman/Downloads/data/spacenet6/split"
config.PREDICTION_ROOT="/home/salman/Downloads/data/spacenet6/predictions"
config.POLY_CSV_ROOT="/home/salman/Downloads/data/spacenet6/polygons"
config.CHECKPOINT_ROOT="/home/salman/Downloads/data/spacenet6/ceckpoints"
config.POLY_OUTPUT_PATH="/home/salman/Downloads/data/spacenet6/val_polygons"
config.freeze()

print(config)

model = get_model(config)
model.eval();

from glob import glob
image_paths = glob(os.path.join(config.INPUT.TEST_IMAGE_DIR, "*.tif"))
#print(image_paths)

preprocessing = get_preprocess(config, is_test=True)
augmentation = get_augmentation(config, is_train=False)

test_dataset = SpaceNet6TestDataset(
    config,
    augmentation=augmentation,
    preprocessing=preprocessing
)

test_dataset_vis = SpaceNet6TestDataset(
    config,
    augmentation=augmentation,
    preprocessing=None
)

channel_footprint = config.INPUT.CLASSES.index('building_footprint')
channel_boundary = config.INPUT.CLASSES.index('building_boundary')

score_thresh = 0.5
alpha = 1.0

start_index = 900
N = 20

for i in range(start_index, start_index + N):
    image_vis = test_dataset_vis[i]['image']
    image = test_dataset[i]['image']

    x_tensor = image.unsqueeze(0).to(config.MODEL.DEVICE)
    pr_score = model.module.predict(x_tensor)
    pr_score = pr_score.squeeze().cpu().numpy()

    pr_score_building = compute_building_score(
        pr_score[channel_footprint],
        pr_score[channel_boundary],
        alpha=alpha
    )
    pr_mask = pr_score_building > score_thresh

    rotated = test_dataset[i]['rotated']
    if rotated:
        image_vis = np.flipud(np.fliplr(image_vis))
        pr_mask = np.flipud(np.fliplr(pr_mask))

    plot_images(
        SAR_intensity_0=(adjust_sar_contrast(image_vis[:, :, 0]), 'gray'),
        building_mask_pr=(pr_mask, 'viridis')
    )
```

The function which this code calls is given below:
def get_spacenet6_preprocess(config, is_test):
    """
    """
    mean_path = os.path.join(
        config.INPUT.MEAN_STD_DIR,
        config.INPUT.IMAGE_TYPE,
        'mean.npy'
    )
    mean = np.load(mean_path)
    mean = mean[np.newaxis, np.newaxis, :]

    std_path = os.path.join(
        config.INPUT.MEAN_STD_DIR,
        config.INPUT.IMAGE_TYPE,
        'std.npy'
    )
    std = np.load(std_path)
    std = std[np.newaxis, np.newaxis, :]

    if is_test:
        to_tensor = albu.Lambda(
            image=functools.partial(_to_tensor)
        )
    else:
        to_tensor = albu.Lambda(
            image=functools.partial(_to_tensor),
            mask=functools.partial(_to_tensor)
        )

    preprocess = [
        albu.Lambda(
            image=functools.partial(
                _normalize_image,
                mean=mean,
                std=std
            )
        ),
        to_tensor,
    ]
    return albu.Compose(preprocess)
